app/routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;

Route::group(['namespace'=>'Project'],function(){
    Route::get('/',             [ 'as'=>'index','uses' => 'SiteController@index']);
    Route::get('/index',        [ 'as'=>'new.index','uses' => 'SiteController@newIndex'])->middleware(['guest']);;
    Route::get('/error',        [ 'as'=>'error',      'uses' => 'SiteController@error']);
    Route::get('/verification-steps', [ 'as'=>'verification.step', 'uses' => 'SiteController@verificationStep']);
    /*
     * API Route for loading and filtering data to the project-list page. although needs to be pulled in a controller
     */
    Route::get('/all','SiteController@loadData');
    Route::get('/fetch-location','SiteController@loadMapData');
    Route::get('/my-investment','SiteController@loadMyInvestmentProjects');
    Route::get('/filter','SiteController@filterProjects');
    Route::get('/latest','SiteController@latestFundedProjects');

});
Route::group([ 'prefix'=>'admin','namespace'=>'Admin', 'as'=>'admin.'],function(){
    Route::get('login',[ 'as'=>'login',      'uses' => 'SiteController@admin']);
});

//Admin Routes
Route::group(['prefix' => 'admin', 'namespace'=>'Admin','middleware' => ['AdminPanelAuth','DisablePreventBack']], function () {
    include_route_files(__DIR__.'/admin/');
});
// Routes accessible after login
Route::group(['middleware' => ['auth','DisablePreventBack']], function (){
    /*
     * Project Routes'.
     */
    Route::group(['prefix' => 'project','namespace' => 'Project'],function(){
        /* DEVELOPER ROUTES*/
        //Developer Routes to create,read,edit and update project and choose plan
        include_route_files(__DIR__.'/project/');
    });

    //Static Data routes
    Route::get('/data/districts/{province_id}',      [ 'as'=>'data.districts', 'uses' => 'DataController@districtsForProvince']);
    Route::get('/data/municipalities/{district_id}', [ 'as'=>'data.municipalities', 'uses' => 'DataController@municipalityForDistrict']);
    Route::get('/data/{payment_id}',                 [ 'as'=>'data.payment', 'uses' => 'DataController@projectDetailsForPayment']);

    //draft routes
    Route::group(['prefix'=>'draft','as'=>'draft.','namespace'=>'Project'],function(){
        Route::get('create',                   [ 'as'=>'create',  'uses' => 'ProjectController@draftCreate']);
        Route::get('{id}',                     [ 'as'=>'edit',    'uses' => 'ProjectController@draftEdit']);
    });

    //SMS Sms Routes
    Route::group(['namespace' => 'Sms'], function(){
        Route::post('/meter/changestatus',['as'=>'meter.change_status','uses'=>'SmsController@changeMeterStatus'])->middleware('AdminPanelAuth');
    });

});

//Routes that help in authentication
Auth::routes();

Route::get('/user/verify/{token}', ['as'=>'user.verify','uses'=>'Auth\RegisterController@verifyUser']);
Route::post('/profile/image', ['as'=>'profile.image','uses'=>'Profile\ProfileController@uploadProfileImage']);
Route::post('/profile/image/delete', ['as'=>'profile.image.delete','uses'=>'Profile\ProfileController@deleteProfileImage']);

Route::group(['middleware' => ['auth','DisablePreventBack'],'namespace'=>'MeterData'], function() {
    include_route_files(__DIR__.'/meterdata/');
});

Route::get('cashflow/{project_id}',[ 'uses' => 'Project\CashFlowController@calculateCashFlow']);

Route::group(['middleware' => ['auth','DisablePreventBack']], function() {
    Route::get('remark/{project_id}',            [ 'as'=>'remark.index',   'uses' => 'RemarksController@index']);
    Route::post('remark/{project_id}/create',    [ 'as'=>'remark.create',  'uses' => 'RemarksController@create']);
});

//Social login routes
Route::get('login/{provider}', 'Auth\LoginController@redirectToProvider')->name('social.login');
Route::post('register/social', 'Auth\RegisterController@registerSocialUser')->name('social.register');
Route::get('login/{provider}/callback','Auth\LoginController@Callback');
Route::get('register/social/waiting','Project\SiteController@socialRegisterWaiting')->name('social.register.waiting');
Route::get('verify/email','Project\SiteController@verifyEmail')->name('verify.email');

Route::group(['middleware' => [ 'auth','InvestorPanelAuth','DisablePreventBack']], function (){
    //New Investment routes
    Route::get('/project-fund/{id}',                    [ 'as'=>'project.detail',               'uses' => 'Investment\InvestmentController@investmentDetail']);
    Route::post('investment/invest',                    [ 'as'=>'investment.checkout.store',    'uses' => 'Investment\InvestmentController@submitCheckout']);
    Route::get('investment/status/{paymentGateway}',    ['as'=>'investment.status',             'uses' =>'Investment\InvestmentController@getPaymentStatus']);
    Route::get('investment/payment-success',            [ 'as'=>'payment.success',              'uses' => 'Investment\InvestmentController@paymentSuccess']);
    Route::get('investment/payment-failure',            [ 'as'=>'payment.failure',              'uses' => 'Investment\InvestmentController@paymentFailure']);
    Route::get('investment/my-investment',              [ 'as'=>'my.investment',                'uses' => 'Investment\InvestmentController@myInvestment']);
    Route::get('/investment/checkout',                        [ 'as'=>'investment.checkout', 'uses' => 'Investment\InvestmentController@checkout']);
    Route::post('project_fund/{project_id}/contact/developer', ['uses'=>'Investment\InvestmentController@contactDeveloper']);
});

Route::group(['middleware' => ['auth']], function (){
    Route::get('/setPassword','Auth\PasswordController@setPasswordForm')->name('password.set.form');
    Route::post('/setPassword','Auth\PasswordController@setPassword')->name('password.set');
    Route::get('/changePassword','Auth\ChangePasswordController@showChangePasswordForm')->name('changePassword.form');
    Route::post('/changePassword','Auth\ChangePasswordController@changePassword')->name('changePassword');
    Route::get('/profile', 'Profile\ProfileController@index')->name('profile.edit');
    Route::post('/profile/update', 'Profile\ProfileController@update')->name('profile.update');
});


/* NEW OGB ADMIN DASHBOARD ROUTES**/
//Email verification routes for partner
Route::get('partner/verify/{token}',                     ['as' => 'ogbadmin.partner.verify',       'uses' => 'OgbAdmin\PartnerController@verifyEmail']);

//routes for partner-user
Route::group(['prefix' => 'partner-user', 'as'=> 'partner-user.','namespace'=>'OgbAdmin'], function () {
    include_route_files(__DIR__.'/partner-user/');
});
Route::get('partner-user/login',[ 'as'=>'partner-user.login',      'uses' => 'Admin\SiteController@partnerUserLogin']);

//new admin routes
include(__DIR__.'/ogbadmin/ogbadmin.php');

Route::get('agent/verify/{token}',                     ['as' => 'ogbadmin.agent.verify',       'uses' => 'OgbAdmin\AgentController@verifyEmail']);
//routes for partner-user
Route::group(['prefix' => 'agent', 'as'=> 'agent.','namespace'=>'OgbAdmin'], function () {
    include_route_files(__DIR__.'/agent/');
});

Route::post('agent/store-temp-user',              ['as' => 'agent.store.temp-user',         'uses' => 'OgbAdmin\AgentController@store'])->middleware('AdminAndPartnerUserCheck');
Route::get('agent/resend-email-verification/{userRegister}',              ['as' => 'agent.resend.email',         'uses' => 'OgbAdmin\AgentController@resendEmailVerification'])->middleware('AdminAndPartnerUserCheck');

//Routes related with account edit
Route::group(['middleware' => ['auth','AdminAndPartnerUserCheck']], function (){
Route::post('account/user/change-image',                 ['as' => 'account.change-image',        'uses' => 'OgbAdmin\AccountController@uploadImage']);
Route::get('account/{partner_user_id}/edit',             ['as' => 'account.edit',                'uses' => 'OgbAdmin\AccountController@edit']);
Route::post('account{partner_user_id}/update',           ['as' => 'account.update',              'uses' => 'OgbAdmin\AccountController@update']);
});

include(__DIR__.'/otp/otp.php');

app/app/Models/Comment.php
<?php

namespace App\Models;

use App\User;
use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    protected $fillable =['comment','commentable_id','commentable_type','user_id','comment_type'];
    public function commentable()
    {
        return $this->morphTo();
    }

    public function user()
    {
        return $this->hasOne(User::class,'user_id','id');
    }

    public function getUsername($user_id)
    {
        return $this->hasOne(User::class,'user_id','id');
    }

    public function getCommenterNameAttribute()
    {
        if(isset($this->user_id)){
            $user = User::findOrFail($this->user_id);
            return $user->full_name;
        }
        return null;
    }


}

app/app/Http/Controllers/RemarksController.php
<?php

namespace App\Http\Controllers;

use App\Enums\Role;
use App\Models\Comment;
use App\Models\Project;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;

class RemarksController extends Controller
{
    //Remarks discussion page
    public function index($project_id)
    {
        $project = Project::with('user')->findOrFail($project_id);
        $remarks = $project->comments->filter(function ($comment) {
            return $comment->comment_type == "remark";
        });

        if (Gate::denies('index', $project)) {
            return redirect()->route('error');
        }
        $default_page = $this->getDefaultPageTitle();
        return view('remark.index', compact('remarks', 'project', 'default_page'));
    }

    //Creates a new remark of project for authenticated user

    public function create(Request $request, $project_id)
    {
        $project = Project::findOrFail($project_id);
        if (Gate::denies('index', $project)) {
            return redirect()->back();
        }
        $request->validate([
            'remark' => 'required|min:5',
        ]);
        $remark = $request->get('remark');
        $project->comments()->create(['comment' => $remark, 'comment_type' => 'remark', 'user_id' => Auth::user()->user_id]);
        $request->session()->flash('success_message', config('messages.remark_success'));
        return redirect()->route('remark.index', $project_id);
    }

    private function getDefaultPageTitle()
    {
        return 'admin.default';

    }
}

app/resources/views/remark/index.blade.php
@extends($default_page)
@section('css')
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
@endsection
@section('content')
    @if (session()->has('success_message'))
        <div class="alert alert-success alert-dismissable">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            {{ session()->get('success_message') }}
        </div>
    @endif
    @include('common.alert')
    <div class="container">
        <div class="row" style="margin-top: 20px">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-body" style="background-color: #f5f5f5">
                        <strong>Project Discussion page</strong>
                        <ul>
                            <li>This page is associated with discussion of project  Id {{$project->id}}.</li>
                            <li>Project is created by:{{$project->user->full_name}}</li>
                            <li>Farmer name: {{$project->farmer_name}} </li>
                        </ul>
                        Please enter the remarks below to discuss about the events......
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                @foreach ($remarks as $remark)
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <a href="#">
                                {{ isset($remark->commenter_name)? $remark->commenter_name:"somebody"}}
                            </a>
                            said {{$remark->created_at->diffForHumans()}}..

                        </div>

                        <div class="panel-body">
                            {{ $remark->comment }}
                        </div>
                    </div>
                @endforeach
            </div>
        </div>

        @if (auth()->check())
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <form method="POST" action="{{route('remark.create',$project->id)}}">
                        {{ csrf_field() }}
                        <div class="form-group">
                            <textarea name="remark" id="remark" class="form-control" placeholder="Have something to say?" rows="5"></textarea>
                        </div>
                        @if ($errors->has('remark'))
                            <span class="help-block">
                                <strong>{{ $errors->first('remark') }}</strong>
                            </span>
                        @endif

                        <button type="submit" class="btn btn-default">Post</button>
                    </form>
                </div>
            </div>
        @else
            <p class="text-center">Please <a href="{{ route('login') }}">sign in</a> to participate in this discussion.</p>
        @endif
    </div>
@endsection